// Exemplos : number
var num1 = 20.94;
var num2 = 3;
var num3 = 0x7BFC;
var num4 = 25;
var num5 = 2039;
console.log("Number - Flutuante...", num1);
console.log("Number - Inteiro...", num2);
console.log("Number - Hexadecimal....", num3);
console.log("Number - Binário...", num4);
console.log("Number - Inteiro...", num5);
